feature {
  name: "Age_xf"
  type: FLOAT
  presence {
    min_fraction: 1.0
  }
  shape {
  }
}
feature {
  name: "Embarked_xf"
  type: INT
  int_domain {
    min: 0
    max: 12
    is_categorical: true
  }
  presence {
    min_fraction: 1.0
  }
  shape {
  }
}
feature {
  name: "Fare_xf"
  type: FLOAT
  presence {
    min_fraction: 1.0
  }
  shape {
  }
}
feature {
  name: "Parch_xf"
  type: INT
  int_domain {
    min: 0
    max: 3
    is_categorical: true
  }
  presence {
    min_fraction: 1.0
  }
  shape {
  }
}
feature {
  name: "Pclass_xf"
  type: INT
  int_domain {
    min: 0
    max: 12
    is_categorical: true
  }
  presence {
    min_fraction: 1.0
  }
  shape {
  }
}
feature {
  name: "Sex_xf"
  type: INT
  int_domain {
    min: 0
    max: 11
    is_categorical: true
  }
  presence {
    min_fraction: 1.0
  }
  shape {
  }
}
feature {
  name: "SibSp_xf"
  type: INT
  int_domain {
    min: 0
    max: 3
    is_categorical: true
  }
  presence {
    min_fraction: 1.0
  }
  shape {
  }
}
feature {
  name: "Survived_xf"
  type: INT
  presence {
    min_fraction: 1.0
  }
  shape {
  }
}
